# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDm8WcmJL4jZhOa83AXgxeWY5ECaHOub
"""
!pip install pytelegrambotapi

import telebot
from telebot import types
from datetime import datetime
import matplotlib.pyplot as plt

MY_TOKEN = "8590324035:AAEIFPKl9zXyXfoch3zGNIG3yT8bvwB_4-0"

bot = telebot.TeleBot(MY_TOKEN)
